//
//  MoviesInterfaces.swift
//  MovieApp
//
//  Created by Oguz Tandogan on 31.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import MovieAppWebService

enum MoviesNavigationOption {
    case movieDetails(String?)
}

protocol MoviesWireframeInterface: WireframeInterface {
    func navigate(option: MoviesNavigationOption)
}

protocol MoviesViewInterface: ViewInterface {
    func reloadData()
    func playLoadingAnimation()
    func stopLoadingAnimation()
    func createAlertViewForResponseError()
}

protocol MoviesPresenterInterface: PresenterInterface {
    func getSearchedMovies(movieId: String?)
    func getRowNumber() -> Int
    func loadTableViewData(at indexPath: IndexPath) -> MoviesListResponseModel?
    func numberOfSections() -> Int
    func didSelectItem(at indexPath: IndexPath)
}

protocol MoviesFormatterInterface: FormatterInterface {
}

protocol MoviesInteractorInterface: InteractorInterface {
    func getSearchedMovies(callback: MoviesCallback, params: MoviesRequestModel)
}
