//
//  MoviesInteractor.swift
//  MovieApp
//
//  Created by Oguz Tandogan on 31.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import MovieAppWebService

final class MoviesInteractor: AssemblerWireframeInteractorProtocol {
    
    private var usecase: MoviesUsecase?
}

// MARK: - Extensions -

extension MoviesInteractor: MoviesInteractorInterface {
    
    func getSearchedMovies(callback: MoviesCallback, params: MoviesRequestModel) {
        DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
            self.usecase = self.returnResolver().resolve(MoviesUsecase.self)
            self.usecase?.execute(useCaseCallBack: callback, params: params)
        }
    }
}
