//
//  MoviesFormatter.swift
//  MovieApp
//
//  Created by Oguz Tandogan on 31.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MoviesFormatter {
}

// MARK: - Extensions -

extension MoviesFormatter: MoviesFormatterInterface {
}
