//
//  MovieDetailsInteractor.swift
//  MovieApp
//
//  Created by Oguz Tandogan on 31.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import MovieAppWebService

final class MovieDetailsInteractor: AssemblerWireframeInteractorProtocol {
    private var usecase: MovieDetailsUsecase!
}

// MARK: - Extensions -

extension MovieDetailsInteractor: MovieDetailsInteractorInterface {
    
    func getMovieDetails(callback: MovieDetailsCallback, params: MovieDetailsRequestModel) {
        self.usecase = self.returnResolver().resolve(MovieDetailsUsecase.self)
        self.usecase?.execute(useCaseCallBack: callback, params: params)
    }
}
