//
//  SplashScreenWireframe.swift
//  MovieApp
//
//  Created by Oguz Tandogan on 31.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class SplashScreenWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "SplashScreen", bundle: nil)

    // MARK: - Module setup -

    init() {
        let moduleViewController = storyboard.instantiateViewController(ofType: SplashScreenViewController.self)
        super.init(viewController: moduleViewController)

        let interactor = SplashScreenInteractor()
        let presenter = SplashScreenPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension SplashScreenWireframe: SplashScreenWireframeInterface {
    
    func navigate(option: SplashScreenNavigationOption) {
        switch option {
        case .movies:
            presentMovies()
        }
    }
    
    private func presentMovies() {
        navigationController?.setRootWireframe(MoviesWireframe())
        
    }
}
