//
//  SplashScreenInterfaces.swift
//  MovieApp
//
//  Created by Oguz Tandogan on 31.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum SplashScreenNavigationOption {
    case movies
}

protocol SplashScreenWireframeInterface: WireframeInterface {
    func navigate(option: SplashScreenNavigationOption)
}

protocol SplashScreenViewInterface: ViewInterface {
}

protocol SplashScreenPresenterInterface: PresenterInterface {
    func renderScreen() -> String
    func navigate()
}

protocol SplashScreenInteractorInterface: InteractorInterface {
}
