//
//  SplashScreenViewController.swift
//  MovieApp
//
//  Created by Oguz Tandogan on 31.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import FirebaseRemoteConfig
import FirebaseCore

final class SplashScreenViewController: UIViewController {

    // MARK: - Public properties -

    @IBOutlet weak var backgroundView: UIView!
    @IBOutlet weak var label: UILabel!
    
    var presenter: SplashScreenPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        NetworkMonitor.shared.startMonitoring(viewController: self)
        fetchTextFromFirebase()
        NetworkMonitor.shared.stopMonitoring()
        setupUI()
    }
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        ColorManager.shared.addGradientBackgroundLayer(view: backgroundView)

    }
    
    private func fetchTextFromFirebase() {
        label.text = presenter.renderScreen()
        DispatchQueue.main.asyncAfter(deadline: .now() + 3) {
            self.presenter.navigate()
        }
    }
    private func setupUI() {
        navigationController?.navigationBar.isHidden = true
    }
}

// MARK: - Extensions -

extension SplashScreenViewController: SplashScreenViewInterface {
}
